exclude: egs/*
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    - id: check-yaml
    - id: trailing-whitespace
    - id: end-of-file-fixer
-   repo: https://github.com/timothycrosley/isort
    rev: 5.3.0
    hooks:
    - id: isort
      args: [--profile, black]
-   repo: https://github.com/psf/black
    rev: 19.10b0
    hooks:
    - id: black
