language: python
dist: xenial
sudo: true
python:
  - 3.6
  - 3.7
  - 3.8

notifications:
  email:
    on_success: change
    on_failure: always

env:
  matrix:
    - PYTORCH_REQUIREMENTS="requirements_pytorch_1.1.0.txt"
    - PYTORCH_REQUIREMENTS="requirements_pytorch_1.2.0.txt"
    - PYTORCH_REQUIREMENTS="requirements_pytorch_1.3.0.txt"
    - PYTORCH_REQUIREMENTS="requirements_pytorch_1.4.0.txt"
    - PYTORCH_REQUIREMENTS=""

before_install:
  # Upgrade PIP to latest version, in order to support --progress-bar
  - pip install -U pip
  # Install dependencies for a particular PyTorch version first.
  - if [ -n "$PYTORCH_REQUIREMENTS" ]; then pip install --progress-bar off -r travis/${PYTORCH_REQUIREMENTS}; fi
  - pip install --progress-bar off .[test]

install: python setup.py install

script: pytest
