language: python
dist: xenial
sudo: true
python:
  - 3.6
  - 3.7
  - 3.8

notifications:
  email:
    on_success: change
    on_failure: always

env:
  matrix:
    - REQUIREMENTS="Pillow>=5.2,<7.0 torch>=1.1.0,<1.2.0 torchvision>=0.2.2,<0.4.0 nnutils-pytorch>=0.3.0,<0.5.0 tqdm==4.19.9"
    - REQUIREMENTS="Pillow>=5.2,<7.0 torch>=1.2.0,<1.3.0 torchvision>=0.4.0,<0.4.1 nnutils-pytorch>=0.5.0,<0.6.0"
    - REQUIREMENTS="Pillow>=5.2,<7.0 torch>=1.3.0,<1.4.0 torchvision>=0.4.1,<0.5.0 nnutils-pytorch>=0.5.0,<0.6.0"
    - REQUIREMENTS="torch>=1.4.0,<1.5.0 torchvision>=0.5.0,<0.6.0 nnutils-pytorch>=0.6.0,<0.7.0"
    - REQUIREMENTS=""

before_install:
  # Upgrade PIP to latest version, in order to support --progress-bar
  - pip install -U pip
  # Install dependencies for a particular PyTorch version first.
  - pip install --progress-bar off torch; # TODO: Remove when github.com/jpuigcerver/nnutils/pull/3 published
  - if [ -n "$REQUIREMENTS" ]; then pip install --progress-bar off ${REQUIREMENTS}; fi

install: pip install --progress-bar off -e ".[test]"

script: pytest
