language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"

notifications:
  email:
    on_success: change
    on_failure: always

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.9
      - g++-4.9

env:
  global:
    - CC=gcc-4.9 CXX=g++-4.9

before_install:
  # Upgrade PIP to latest version, in order to support --progres-bar
  - pip install -U pip
  # Manually install torch, since it is required in the setup of nnutils
  - pip install torch --progress-bar off
  - pip install cffi --progress-bar off

install:
  - python setup.py install
  #- ./travis/build_nnutils.sh
  - ./travis/build_warp_ctc.sh

script:
  - ./travis/run_tests.sh
