language: python
dist: xenial
sudo: true
python:
  - 3.6
  - 3.7
  - 3.8

notifications:
  email:
    on_success: change
    on_failure: always

env:
  matrix:
    - REQUIREMENTS="torch>=1.4.0,<1.5.0 torchvision>=0.5.0,<0.6.0 nnutils-pytorch>=0.6.0,<0.7.0"
    - REQUIREMENTS=""

before_install:
  # Upgrade PIP to latest version, in order to support --progress-bar
  - pip install -U pip
  # Install dependencies for a particular PyTorch version first.
  - pip install --progress-bar off torch; # TODO: Remove when github.com/jpuigcerver/nnutils/pull/3 published
  - if [ -n "$REQUIREMENTS" ]; then pip install --progress-bar off ${REQUIREMENTS}; fi

install: pip install --progress-bar off -e ".[test]"

script: pytest
