language: python
dist: xenial
sudo: true
python:
  - 3.5
  - 3.6
  - 3.7

notifications:
  email:
    on_success: change
    on_failure: always

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.9
      - g++-4.9

env:
  global:
    - CC=gcc-4.9 CXX=g++-4.9

before_install:
  # Upgrade PIP to latest version, in order to support --progres-bar
  - python -m pip install -U pip
  # Manually install torch, since it is required in the setup of nnutils
  - python -m pip install numpy --progress-bar off
  - ./travis/install_pytorch.sh
  - python -m pip install nnutils-pytorch --progress-bar off
  - python -m pip install torch-baidu-ctc --progress-bar off

install:
  - python setup.py install

script:
  - ./travis/run_tests.sh
