site:
  title: Teklia Documentation
  start_page: pylaia::index.adoc
content:
  sources:
  - url: .
    branches: HEAD
    start_path: antora
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
