name: Laia CI

on:
  push:
    branches: [master]
  pull_request:
  schedule:
    # at 07:00 on Sunday
    - cron: '0 7 * * sun'

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Run pre-commit
        run: |
          pip install pre-commit
          pre-commit run --all-files

  pytest:
    name: Python ${{ matrix.python-version }} - PyTorch ${{ matrix.torch-version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.9, 3.8, 3.7, 3.6]
        torch-version: [1.7.*, 1.6.*, 1.5.*, 1.4.*]
        include:
          # fix torchvision and nnutils versions for each torch version
          - torch-version: 1.7.*
            # TODO: update when released
            nnutils-version: 1.6.*
            torchvision-version: 0.8.*
          - torch-version: 1.6.*
            nnutils-version: 1.6.*
            torchvision-version: 0.7.*
          - torch-version: 1.5.*
            nnutils-version: 1.5.*
            torchvision-version: 0.6.*
          - torch-version: 1.4.*
            nnutils-version: 1.4.*
            torchvision-version: 0.5.*
        exclude:
          # TODO: NumPy does not support 3.9 yet
          - python-version: 3.9
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Configure requirements
      run: |
        sed -i s/^torch$/torch==${{ matrix.torch-version }}/ requirements.txt
        sed -i s/^torchvision$/torchvision==${{ matrix.torchvision-version }}/ requirements.txt
        sed -i s/^nnutils-pytorch$/nnutils-pytorch==${{ matrix.nnutils-version }}/ requirements.txt
    - name: Install requirements
      run: pip install -e .[test]
    - name: Run pytest
      run: pytest --cov=laia tests
    - uses: codecov/codecov-action@v1
