name: Laia CI

on:
  push:
    branches: [master]
    paths-ignore: ['README.md']
  pull_request:
  schedule:
    # at 07:00 on Sunday
    - cron: '0 7 * * sun'

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Run pre-commit
        run: |
          pip install pre-commit
          pre-commit run --all-files

  pytest:
    name: Python ${{ matrix.python }} - PyTorch ${{ matrix.torch }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        # TODO: include 3.9 when NumPy adds support
        python: [3.8, 3.7, 3.6]
        # TODO: include 1.7.* when 1.7.1 is released
        torch: [1.6.*, 1.5.*, 1.4.*]
        # fix torchvision and nnutils versions for each torch version
        include:
          #- torch: 1.7.*
          #  # TODO: update when released
          #  nnutils: 1.6.*
          #  torchvision: 0.8.*
          - torch: 1.6.*
            nnutils: 1.6.*
            torchvision: 0.7.*
          - torch: 1.5.*
            nnutils: 1.5.*
            torchvision: 0.6.*
          - torch: 1.4.*
            nnutils: 1.4.*
            torchvision: 0.5.*
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}
    - name: Configure requirements
      run: |
        sed -i s/^torch$/torch==${{ matrix.torch }}/ requirements.txt
        sed -i s/^torchvision$/torchvision==${{ matrix.torchvision }}/ requirements.txt
        sed -i s/^nnutils-pytorch$/nnutils-pytorch==${{ matrix.nnutils }}/ requirements.txt
    - name: Install requirements
      run: pip install -e .[test]
    - name: Run pytest
      run: pytest --cov=laia tests
    - uses: codecov/codecov-action@v1
      # upload coverage only for main job
      if: ${{ matrix.python == '3.8' && matrix.torch == '1.6.*'}}
